services:
  - type: web
    name: staffcloud
    env: python
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py